insert into public.wilayas (code, name)
values
  ('01', 'Adrar'),
  ('02', 'Chlef'),
  ('03', 'Laghouat'),
  ('04', 'Oum El Bouaghi'),
  ('05', 'Batna'),
  ('06', 'Bejaia'),
  ('07', 'Biskra'),
  ('08', 'Bechar'),
  ('09', 'Blida'),
  ('10', 'Bouira'),
  ('11', 'Tamanrasset'),
  ('12', 'Tebessa'),
  ('13', 'Tlemcen'),
  ('14', 'Tiaret'),
  ('15', 'Tizi Ouzou'),
  ('16', 'Alger'),
  ('17', 'Djelfa'),
  ('18', 'Jijel'),
  ('19', 'Setif'),
  ('20', 'Saida'),
  ('21', 'Skikda'),
  ('22', 'Sidi Bel Abbes'),
  ('23', 'Annaba'),
  ('24', 'Guelma'),
  ('25', 'Constantine'),
  ('26', 'Medea'),
  ('27', 'Mostaganem'),
  ('28', 'M''Sila'),
  ('29', 'Mascara'),
  ('30', 'Ouargla'),
  ('31', 'Oran'),
  ('32', 'El Bayadh'),
  ('33', 'Illizi'),
  ('34', 'Bordj Bou Arreridj'),
  ('35', 'Boumerdes'),
  ('36', 'El Tarf'),
  ('37', 'Tindouf'),
  ('38', 'Tissemsilt'),
  ('39', 'El Oued'),
  ('40', 'Khenchela'),
  ('41', 'Souk Ahras'),
  ('42', 'Tipaza'),
  ('43', 'Mila'),
  ('44', 'Ain Defla'),
  ('45', 'Naama'),
  ('46', 'Ain Temouchent'),
  ('47', 'Ghardaia'),
  ('48', 'Relizane'),
  ('49', 'Timimoun'),
  ('50', 'Bordj Badji Mokhtar'),
  ('51', 'Ouled Djellal'),
  ('52', 'Beni Abbes'),
  ('53', 'In Salah'),
  ('54', 'In Guezzam'),
  ('55', 'Touggourt'),
  ('56', 'Djanet'),
  ('57', 'El M''Ghair'),
  ('58', 'El Menia')
on conflict (code) do update set name = excluded.name;

insert into public.communes (wilaya_id, name)
select w.id, v.name
from (values
  ('01', 'Adrar'),
  ('01', 'Tamest'),
  ('01', 'Reggane'),
  ('01', 'In Zghmir'),
  ('01', 'Tit'),
  ('01', 'Tsabit'),
  ('01', 'Zaouiet Kounta'),
  ('01', 'Aoulef'),
  ('01', 'Tamekten'),
  ('01', 'Tamantit'),
  ('01', 'Fenoughil'),
  ('01', 'Sali'),
  ('01', 'Akabli'),
  ('01', 'Ouled Ahmed Tammi'),
  ('01', 'Bouda'),
  ('01', 'Sebaa'),
  ('02', 'Abou El Hassan'),
  ('02', 'An Merane'),
  ('02', 'Bnairia'),
  ('02', 'Beni Bouateb'),
  ('02', 'Beni Haoua'),
  ('02', 'Beni Rached'),
  ('02', 'Boukadir'),
  ('02', 'Bouzeghaia'),
  ('02', 'Breira'),
  ('02', 'Chettia'),
  ('02', 'Chlef'),
  ('02', 'Dahra'),
  ('02', 'El Hadjadj'),
  ('02', 'El Karimia'),
  ('02', 'El Marsa'),
  ('02', 'Harchoun'),
  ('02', 'Harenfa'),
  ('02', 'Labiod Medjadja'),
  ('02', 'Moussadek'),
  ('02', 'Oued Fodda'),
  ('02', 'Oued Goussine'),
  ('02', 'Oued Sly'),
  ('02', 'Ouled Abbes'),
  ('02', 'Ouled Ben Abdelkader'),
  ('02', 'Ouled Fares'),
  ('02', 'Oum Drou'),
  ('02', 'Sendjas'),
  ('02', 'Sidi Abderrahmane'),
  ('02', 'Sidi Akkacha'),
  ('02', 'Sobha'),
  ('02', 'Tadjena'),
  ('02', 'Talassa'),
  ('02', 'Taougrite'),
  ('02', 'Tns'),
  ('02', 'Zeboudja'),
  ('03', 'Laghouat'),
  ('03', 'Ksar El Hirane'),
  ('03', 'Bennasser Benchohra'),
  ('03', 'Sidi Makhlouf'),
  ('03', 'Hassi Delaa'),
  ('03', 'Hassi R''Mel'),
  ('03', 'An Madhi'),
  ('03', 'Tadjemout'),
  ('03', 'Kheneg'),
  ('03', 'Gueltat Sidi Saad'),
  ('03', 'An Sidi Ali'),
  ('03', 'Beidha'),
  ('03', 'Brida'),
  ('03', 'El Ghicha'),
  ('03', 'Hadj Mechri'),
  ('03', 'Sebgag'),
  ('03', 'Taouiala'),
  ('03', 'Tadjrouna'),
  ('03', 'Aflou'),
  ('03', 'El Assafia'),
  ('03', 'Oued Morra'),
  ('03', 'Oued M''Zi'),
  ('03', 'El Houaita'),
  ('03', 'Sidi Bouzid'),
  ('04', 'Oum el Bouaghi'),
  ('04', 'An Beda'),
  ('04', 'An M''lila'),
  ('04', 'Behir Chergui'),
  ('04', 'El Amiria'),
  ('04', 'Sigus'),
  ('04', 'El Belala'),
  ('04', 'An Babouche'),
  ('04', 'Berriche'),
  ('04', 'Ouled Hamla'),
  ('04', 'Dhalaa'),
  ('04', 'An Kercha'),
  ('04', 'Hanchir Toumghani'),
  ('04', 'El Djazia'),
  ('04', 'An Diss'),
  ('04', 'Fkirina'),
  ('04', 'Souk Naamane'),
  ('04', 'Zorg'),
  ('04', 'El Fedjoudj Boughrara Saoudi'),
  ('04', 'Ouled Zoua'),
  ('04', 'Bir Chouhada'),
  ('04', 'Ksar Sbahi'),
  ('04', 'Oued Nini'),
  ('04', 'Meskiana'),
  ('04', 'An Fakroun'),
  ('04', 'Rahia'),
  ('04', 'An Zitoun'),
  ('04', 'Ouled Gacem'),
  ('04', 'El Harmilia'),
  ('05', 'Batna'),
  ('05', 'Ghassira'),
  ('05', 'Maafa'),
  ('05', 'Merouana'),
  ('05', 'Seriana'),
  ('05', 'Menaa'),
  ('05', 'El Madher'),
  ('05', 'Tazoult'),
  ('05', 'N''Gaous'),
  ('05', 'Guigba'),
  ('05', 'Inoughissen'),
  ('05', 'Ouyoun El Assafir'),
  ('05', 'Djerma'),
  ('05', 'Bitam'),
  ('05', 'Abdelkader Azil'),
  ('05', 'Arris'),
  ('05', 'Kimmel'),
  ('05', 'Tilatou'),
  ('05', 'An Djasser'),
  ('05', 'Ouled Sellam'),
  ('05', 'Tigherghar'),
  ('05', 'An Yagout'),
  ('05', 'Fesdis'),
  ('05', 'Sefiane'),
  ('05', 'Rahbat'),
  ('05', 'Tighanimine'),
  ('05', 'Lemsane'),
  ('05', 'Ksar Bellezma'),
  ('05', 'Seggana'),
  ('05', 'Ichmoul'),
  ('05', 'Foum Toub'),
  ('05', 'Ben Foudhala El Hakania'),
  ('05', 'Oued El Ma'),
  ('05', 'Talkhamt'),
  ('05', 'Bouzina'),
  ('05', 'Chemora'),
  ('05', 'Oued Chaaba'),
  ('05', 'Taxlent'),
  ('05', 'Gosbat'),
  ('05', 'Ouled Aouf'),
  ('05', 'Boumagueur'),
  ('05', 'Barika'),
  ('05', 'Djezar'),
  ('05', 'T''Kout'),
  ('05', 'An Touta'),
  ('05', 'Hidoussa'),
  ('05', 'Teniet El Abed'),
  ('05', 'Oued Taga'),
  ('05', 'Ouled Fadel'),
  ('05', 'Timgad'),
  ('05', 'Ras El Aioun'),
  ('05', 'Chir'),
  ('05', 'Ouled Si Slimane'),
  ('05', 'Zanat El Beida'),
  ('05', 'M''doukel'),
  ('05', 'Ouled Ammar'),
  ('05', 'El Hassi'),
  ('05', 'Lazrou'),
  ('05', 'Boumia (Batna)'),
  ('05', 'Boulhilat'),
  ('05', 'Larba'),
  ('07', 'An Naga'),
  ('07', 'An Zaatout'),
  ('07', 'Biskra'),
  ('07', 'Bordj Ben Azzouz'),
  ('07', 'Bouchagroune'),
  ('07', 'Branis'),
  ('07', 'Chetma'),
  ('07', 'Djemorah'),
  ('07', 'El Feidh'),
  ('07', 'El Ghrous'),
  ('07', 'El Hadjeb'),
  ('07', 'El Haouch'),
  ('07', 'El Kantara'),
  ('07', 'El Mizaraa'),
  ('07', 'El Outaya'),
  ('07', 'Foughala'),
  ('07', 'Khenguet Sidi Nadji'),
  ('07', 'Lichana'),
  ('07', 'Lioua'),
  ('07', 'M''Chouneche'),
  ('07', 'Mekhadma'),
  ('07', 'M''Lili'),
  ('07', 'Oumache'),
  ('07', 'Ourlal'),
  ('07', 'Sidi Okba'),
  ('07', 'Tolga'),
  ('07', 'Zeribet El Oued'),
  ('09', 'Blida'),
  ('09', 'Chebli'),
  ('09', 'Bouinan'),
  ('09', 'Oued Alleug'),
  ('09', 'Ouled Yach'),
  ('09', 'Chra'),
  ('09', 'El Affroun'),
  ('09', 'Chiffa'),
  ('09', 'Hammam Melouane'),
  ('09', 'Benkhelil'),
  ('09', 'Soumaa'),
  ('09', 'Mouzaia'),
  ('09', 'Souhane'),
  ('09', 'Meftah'),
  ('09', 'Ouled Slama'),
  ('09', 'Boufarik'),
  ('09', 'Larbaa'),
  ('09', 'Oued Djer'),
  ('09', 'Beni Tamou'),
  ('09', 'Bouarfa'),
  ('09', 'Beni Mered'),
  ('09', 'Bougara'),
  ('09', 'Guerouaou'),
  ('09', 'An Romana'),
  ('09', 'Djebabra'),
  ('10', 'An Bessem'),
  ('10', 'Hanif'),
  ('10', 'Aghbalou'),
  ('10', 'An El Hadjar'),
  ('10', 'Ahl El Ksar'),
  ('10', 'An Laloui'),
  ('10', 'Ath Mansour'),
  ('10', 'Aomar'),
  ('10', 'An El Turc'),
  ('10', 'At Laziz'),
  ('10', 'Bouderbala'),
  ('10', 'Bechloul'),
  ('10', 'Bir Ghbalou'),
  ('10', 'Boukram'),
  ('10', 'Bordj Okhriss'),
  ('10', 'Bouira'),
  ('10', 'Chorfa'),
  ('10', 'Dechmia'),
  ('10', 'Dirrah'),
  ('10', 'Djebahia'),
  ('10', 'El Hakimia'),
  ('10', 'El Hachimia'),
  ('10', 'El Adjiba'),
  ('10', 'El Khabouzia'),
  ('10', 'El Mokrani'),
  ('10', 'El Asnam'),
  ('10', 'Guerrouma'),
  ('10', 'Haizer'),
  ('10', 'Hadjera Zerga'),
  ('10', 'Kadiria'),
  ('10', 'Lakhdaria'),
  ('10', 'M''Chedallah'),
  ('10', 'Mezdour'),
  ('10', 'Maala'),
  ('10', 'Maamora'),
  ('10', 'Oued El Berdi'),
  ('10', 'Ouled Rached'),
  ('10', 'Raouraoua'),
  ('10', 'Ridane'),
  ('10', 'Saharidj'),
  ('10', 'Sour El Ghouzlane'),
  ('10', 'Souk El Khemis'),
  ('10', 'Taguedit'),
  ('10', 'Taghzout'),
  ('10', 'Zbarbar'),
  ('11', 'Tamanrasset'),
  ('11', 'Abalessa'),
  ('11', 'Idles'),
  ('11', 'Tazrouk'),
  ('11', 'In Amguel'),
  ('13', 'Tlemcen'),
  ('13', 'Beni Mester'),
  ('13', 'An Tallout'),
  ('13', 'Remchi'),
  ('13', 'El Fehoul'),
  ('13', 'Sabra'),
  ('13', 'Ghazaouet'),
  ('13', 'Souani'),
  ('13', 'Djebala'),
  ('13', 'El Gor'),
  ('13', 'Oued Lakhdar'),
  ('13', 'An Fezza'),
  ('13', 'Ouled Mimoun'),
  ('13', 'Amieur'),
  ('13', 'An Youcef'),
  ('13', 'Zenata'),
  ('13', 'Beni Snous'),
  ('13', 'Bab El Assa'),
  ('13', 'Dar Yaghmouracene'),
  ('13', 'Fellaoucene'),
  ('13', 'Azails'),
  ('13', 'Sebaa Chioukh'),
  ('13', 'Terny Beni Hdiel'),
  ('13', 'Bensekrane'),
  ('13', 'An Nehala'),
  ('13', 'Hennaya'),
  ('13', 'Maghnia'),
  ('13', 'Hammam Boughrara'),
  ('13', 'Souahlia'),
  ('13', 'MSirda Fouaga'),
  ('13', 'An Fetah'),
  ('13', 'El Aricha'),
  ('13', 'Souk Tlata'),
  ('13', 'Sidi Abdelli'),
  ('13', 'Sebdou'),
  ('13', 'Beni Ouarsous'),
  ('13', 'Sidi Medjahed'),
  ('13', 'Beni Boussaid'),
  ('13', 'Marsa Ben M''Hidi'),
  ('13', 'Nedroma'),
  ('13', 'Sidi Djillali'),
  ('13', 'Beni Bahdel'),
  ('13', 'El Bouihi'),
  ('13', 'Honane'),
  ('13', 'Tienet'),
  ('13', 'Ouled Riyah'),
  ('13', 'Bouhlou'),
  ('13', 'Beni Khellad'),
  ('13', 'An Ghoraba'),
  ('13', 'Chetouane'),
  ('13', 'Mansourah'),
  ('13', 'Beni Semiel'),
  ('13', 'An Kebira'),
  ('14', 'An Bouchekif'),
  ('14', 'An Deheb'),
  ('14', 'An El Hadid'),
  ('14', 'An Kermes'),
  ('14', 'An Dzarit'),
  ('14', 'Bougara'),
  ('14', 'Chehaima'),
  ('14', 'Dahmouni'),
  ('14', 'Djebilet Rosfa'),
  ('14', 'Djillali Ben Amar'),
  ('14', 'Faidja'),
  ('14', 'Frenda'),
  ('14', 'Guertoufa'),
  ('14', 'Hamadia'),
  ('14', 'Ksar Chellala'),
  ('14', 'Madna'),
  ('14', 'Mahdia'),
  ('14', 'Mechraa Safa'),
  ('14', 'Medrissa'),
  ('14', 'Medroussa'),
  ('14', 'Meghila'),
  ('14', 'Mellakou'),
  ('14', 'Nadorah'),
  ('14', 'Naima'),
  ('14', 'Oued Lilli'),
  ('14', 'Rahouia'),
  ('14', 'Rechaiga'),
  ('14', 'Sebaine'),
  ('14', 'Sebt'),
  ('14', 'Serghine'),
  ('14', 'Si Abdelghani'),
  ('14', 'Sidi Abderahmane'),
  ('14', 'Sidi Ali Mellal'),
  ('14', 'Sidi Bakhti'),
  ('14', 'Sidi Hosni'),
  ('14', 'Sougueur'),
  ('14', 'Tagdemt'),
  ('14', 'Takhemaret'),
  ('14', 'Tiaret'),
  ('14', 'Tidda'),
  ('14', 'Tousnina'),
  ('14', 'Zmalet El Emir Abdelkader'),
  ('15', 'Tizi Ouzou'),
  ('15', 'Ain El Hammam'),
  ('15', 'Akbil'),
  ('15', 'Freha'),
  ('15', 'Souama'),
  ('15', 'Mechtras'),
  ('15', 'Irdjen'),
  ('15', 'Timizart'),
  ('15', 'Makouda'),
  ('15', 'Dra El Mizan'),
  ('15', 'Tizi Gheniff'),
  ('15', 'Bounouh'),
  ('15', 'At Chafa'),
  ('15', 'Frikat'),
  ('15', 'Beni Assi'),
  ('15', 'Beni Zmenzer'),
  ('15', 'Iferhounne'),
  ('15', 'Azazga'),
  ('15', 'Illoula Oumalou'),
  ('15', 'Yakouren'),
  ('15', 'Larba Nath Irathen'),
  ('15', 'Tizi Rached'),
  ('15', 'Zekri'),
  ('15', 'Ouaguenoun'),
  ('15', 'An Zaouia'),
  ('15', 'M''Kira'),
  ('15', 'At Yahia'),
  ('15', 'At Mahmoud'),
  ('15', 'Matkas'),
  ('15', 'At Boumahdi'),
  ('15', 'Abi Youcef'),
  ('15', 'Beni Douala'),
  ('15', 'Illilten'),
  ('15', 'Bouzguen'),
  ('15', 'At Aggouacha'),
  ('15', 'Ouadhia'),
  ('15', 'Azeffoun'),
  ('15', 'Tigzirt'),
  ('15', 'At Assa Mimoun'),
  ('15', 'Boghni'),
  ('15', 'Ifigha'),
  ('15', 'At Oumalou'),
  ('15', 'Tirmitine'),
  ('15', 'Akerrou'),
  ('15', 'Yatafen'),
  ('15', 'Ath Zikki'),
  ('15', 'Dra Ben Khedda'),
  ('15', 'Ouacif'),
  ('15', 'Idjeur'),
  ('15', 'Mekla'),
  ('15', 'Tizi N''Tleta'),
  ('15', 'At Yenni'),
  ('15', 'Aghribs'),
  ('15', 'Iflissen'),
  ('15', 'Boudjima'),
  ('15', 'At Yahia Moussa'),
  ('15', 'Souk El Thenine'),
  ('15', 'At Khellili'),
  ('15', 'Sidi Namane'),
  ('15', 'Iboudraren'),
  ('15', 'Agouni Gueghrane'),
  ('15', 'Mizrana'),
  ('15', 'Imsouhel'),
  ('15', 'Tadmat'),
  ('15', 'At Bouadou'),
  ('15', 'Assi Youcef'),
  ('15', 'At Toudert'),
  ('16', 'Alger Centre'),
  ('16', 'Sidi M''Hamed'),
  ('16', 'El Madania'),
  ('16', 'Belouizdad'),
  ('16', 'Bab El Oued'),
  ('16', 'Bologhine'),
  ('16', 'Casbah'),
  ('16', 'Oued Koriche'),
  ('16', 'Bir Mourad Ras'),
  ('16', 'El Biar'),
  ('16', 'Bouzareah'),
  ('16', 'Birkhadem'),
  ('16', 'El Harrach'),
  ('16', 'Baraki'),
  ('16', 'Oued Smar'),
  ('16', 'Bachdjerrah'),
  ('16', 'Hussein Dey'),
  ('16', 'Kouba'),
  ('16', 'Bourouba'),
  ('16', 'Dar El Beda'),
  ('16', 'Bab Ezzouar'),
  ('16', 'Ben Aknoun'),
  ('16', 'Dely Ibrahim'),
  ('16', 'El Hammamet'),
  ('16', 'Ras Hamidou'),
  ('16', 'Djasr Kasentina'),
  ('16', 'El Mouradia'),
  ('16', 'Hydra'),
  ('16', 'Mohammadia'),
  ('16', 'Bordj El Kiffan'),
  ('16', 'El Magharia'),
  ('16', 'Beni Messous'),
  ('16', 'Les Eucalyptus'),
  ('16', 'Birtouta'),
  ('16', 'Tessala El Merdja'),
  ('16', 'Ouled Chebel'),
  ('16', 'Sidi Moussa'),
  ('16', 'An Taya'),
  ('16', 'Bordj El Bahri'),
  ('16', 'El Marsa'),
  ('16', 'H''raoua'),
  ('16', 'Rouba'),
  ('16', 'Reghaa'),
  ('16', 'An Benian'),
  ('16', 'Staoueli'),
  ('16', 'Zeralda'),
  ('16', 'Mahelma'),
  ('16', 'Rahmania'),
  ('16', 'Souidania'),
  ('16', 'Cheraga'),
  ('16', 'Ouled Fayet'),
  ('16', 'El Achour'),
  ('16', 'Draria'),
  ('16', 'Douera'),
  ('16', 'Baba Hassen'),
  ('16', 'Khraicia'),
  ('16', 'Saoula'),
  ('17', 'An Chouhada'),
  ('17', 'An El Ibel'),
  ('17', 'An Feka'),
  ('17', 'An Maabed'),
  ('17', 'An Oussara'),
  ('17', 'Amourah'),
  ('17', 'Benhar'),
  ('17', 'Beni Yagoub'),
  ('17', 'Birine'),
  ('17', 'Bouira Lahdab'),
  ('17', 'Charef'),
  ('17', 'Dar Chioukh'),
  ('17', 'Deldoul'),
  ('17', 'Djelfa'),
  ('17', 'Douis'),
  ('17', 'El Guedid'),
  ('17', 'El Idrissia'),
  ('17', 'El Khemis'),
  ('17', 'Faidh El Botma'),
  ('17', 'Guernini'),
  ('17', 'Guettara'),
  ('17', 'Had Sahary'),
  ('17', 'Hassi Bahbah'),
  ('17', 'Hassi El Euch'),
  ('17', 'Hassi Fedoul'),
  ('17', 'Messaad'),
  ('17', 'M''Liliha'),
  ('17', 'Moudjebara'),
  ('17', 'Oum Laadham'),
  ('17', 'Sed Rahal'),
  ('17', 'Selmana'),
  ('17', 'Sidi Baizid'),
  ('17', 'Sidi Ladjel'),
  ('17', 'Tadmit'),
  ('17', 'Zaafrane'),
  ('17', 'Zaccar'),
  ('18', 'Jijel'),
  ('18', 'Eraguene'),
  ('18', 'El Aouana'),
  ('18', 'Ziama Mansouriah'),
  ('18', 'Taher'),
  ('18', 'Emir Abdelkader'),
  ('18', 'Chekfa'),
  ('18', 'Chahna'),
  ('18', 'El Milia'),
  ('18', 'Sidi Maarouf'),
  ('18', 'Settara'),
  ('18', 'El Ancer'),
  ('18', 'Sidi Abdelaziz'),
  ('18', 'Kaous'),
  ('18', 'Ghebala'),
  ('18', 'Bouraoui Belhadef'),
  ('18', 'Djimla'),
  ('18', 'Selma Benziada'),
  ('18', 'Boucif Ouled Askeur'),
  ('18', 'El Kennar Nouchfi'),
  ('18', 'Ouled Yahia Khedrouche'),
  ('18', 'Boudriaa Ben Yadjis'),
  ('18', 'Kheri Oued Adjoul'),
  ('18', 'Texenna'),
  ('18', 'Djemaa Beni Habibi'),
  ('18', 'Bordj Tahar'),
  ('18', 'Ouled Rabah'),
  ('18', 'Ouadjana'),
  ('21', 'An Bouziane'),
  ('21', 'An Charchar'),
  ('21', 'An Kechra'),
  ('21', 'An Zouit'),
  ('21', 'Azzaba'),
  ('21', 'Bekkouche Lakhdar'),
  ('21', 'Bin El Ouiden'),
  ('21', 'Ben Azzouz'),
  ('21', 'Beni Bechir'),
  ('21', 'Beni Oulbane'),
  ('21', 'Beni Zid'),
  ('21', 'Bouchtata'),
  ('21', 'Cheraia'),
  ('21', 'Collo'),
  ('21', 'Djendel Saadi Mohamed'),
  ('21', 'El Ghedir'),
  ('21', 'El Hadaiek'),
  ('21', 'El Harrouch'),
  ('21', 'El Marsa'),
  ('21', 'Emdjez Edchich'),
  ('21', 'Es Sebt'),
  ('21', 'Filfila'),
  ('21', 'Hamadi Krouma'),
  ('21', 'Kanoua'),
  ('21', 'Kerkera'),
  ('21', 'Kheneg Mayoum'),
  ('21', 'Oued Zehour'),
  ('21', 'Ouldja Boulballout'),
  ('21', 'Ouled Attia'),
  ('21', 'Ouled Hbaba'),
  ('21', 'Oum Toub'),
  ('21', 'Ramdane Djamel'),
  ('21', 'Salah Bouchaour'),
  ('21', 'Sidi Mezghiche'),
  ('21', 'Skikda'),
  ('21', 'Tamalous'),
  ('21', 'Zerdaza'),
  ('21', 'Zitouna'),
  ('23', 'Annaba'),
  ('23', 'Berrahal'),
  ('23', 'El Hadjar'),
  ('23', 'Eulma'),
  ('23', 'El Bouni'),
  ('23', 'Oued El Aneb'),
  ('23', 'Cheurfa'),
  ('23', 'Seradi'),
  ('23', 'An Berda'),
  ('23', 'Chetabi'),
  ('23', 'Sidi Amar'),
  ('23', 'Treat'),
  ('24', 'An Ben Beida'),
  ('24', 'An Larbi'),
  ('24', 'An Makhlouf'),
  ('24', 'An Reggada'),
  ('24', 'An Sandel'),
  ('24', 'Belkheir'),
  ('24', 'Ben Djerrah'),
  ('24', 'Beni Mezline'),
  ('24', 'Bordj Sabath'),
  ('24', 'Bouhachana'),
  ('24', 'Bouhamdane'),
  ('24', 'Bouati Mahmoud'),
  ('24', 'Bouchegouf'),
  ('24', 'Boumahra Ahmed'),
  ('24', 'Dahouara'),
  ('24', 'Djeballah Khemissi'),
  ('24', 'El Fedjoudj'),
  ('24', 'Guellat Bou Sbaa'),
  ('24', 'Guelma'),
  ('24', 'Hammam Debagh'),
  ('24', 'Hammam N''Bail'),
  ('24', 'Hliopolis'),
  ('24', 'Houari Boumdine'),
  ('24', 'Khezarra'),
  ('24', 'Medjez Amar'),
  ('24', 'Medjez Sfa'),
  ('24', 'Nechmaya'),
  ('24', 'Oued Cheham'),
  ('24', 'Oued Fragha'),
  ('24', 'Oued Zenati'),
  ('24', 'Ras El Agba'),
  ('24', 'Roknia'),
  ('24', 'Sellaoua Announa'),
  ('24', 'Tamlouka'),
  ('25', 'An Abid'),
  ('25', 'An Smara'),
  ('25', 'Beni Hamiden'),
  ('25', 'Constantine'),
  ('25', 'Didouche Mourad'),
  ('25', 'El Khroub'),
  ('25', 'Hamma Bouziane'),
  ('25', 'Ibn Badis'),
  ('25', 'Ibn Ziad'),
  ('25', 'Messaoud Boudjriou'),
  ('25', 'Ouled Rahmoune'),
  ('25', 'Zighoud Youcef'),
  ('27', 'Abdelmalek Ramdane'),
  ('27', 'Achaacha'),
  ('27', 'An Boudinar'),
  ('27', 'An Nouissy'),
  ('27', 'An Sidi Cherif'),
  ('27', 'An Tedles'),
  ('27', 'Blad Touahria'),
  ('27', 'Bouguirat'),
  ('27', 'El Hassaine'),
  ('27', 'Fornaka'),
  ('27', 'Hadjadj'),
  ('27', 'Hassi Mameche'),
  ('27', 'Khadra'),
  ('27', 'Kheireddine'),
  ('27', 'Mansourah'),
  ('27', 'Mesra'),
  ('27', 'Mazagran'),
  ('27', 'Mostaganem'),
  ('27', 'Nekmaria'),
  ('27', 'Oued El Kheir'),
  ('27', 'Ouled Boughalem'),
  ('27', 'Ouled Maallah'),
  ('27', 'Safsaf'),
  ('27', 'Sayada'),
  ('27', 'Sidi Ali'),
  ('27', 'Sidi Belattar'),
  ('27', 'Sidi Lakhdar'),
  ('27', 'Sirat'),
  ('27', 'Souaflia'),
  ('27', 'Sour'),
  ('27', 'Stidia'),
  ('27', 'Tazgait'),
  ('28', 'An El Hadjel'),
  ('28', 'An El Melh'),
  ('28', 'An Errich'),
  ('28', 'An Fares'),
  ('28', 'An Khadra'),
  ('28', 'Belaiba'),
  ('28', 'Ben Srour'),
  ('28', 'Beni Ilmane'),
  ('28', 'Benzouh'),
  ('28', 'Berhoum'),
  ('28', 'Bir Foda'),
  ('28', 'Bou Sada'),
  ('28', 'Bouti Sayah'),
  ('28', 'Chellal'),
  ('28', 'Dehahna'),
  ('28', 'Djebel Messaad'),
  ('28', 'El Hamel'),
  ('28', 'El Houamed'),
  ('28', 'Hammam Dhalaa'),
  ('28', 'Khettouti Sed El Djir'),
  ('28', 'Khoubana'),
  ('28', 'Maadid'),
  ('28', 'Maarif'),
  ('28', 'Magra'),
  ('28', 'M''Cif'),
  ('28', 'Medjedel'),
  ('28', 'Mohammed Boudiaf'),
  ('28', 'M''Sila'),
  ('28', 'M''Tarfa'),
  ('28', 'Ouanougha'),
  ('28', 'Ouled Addi Guebala'),
  ('28', 'Ouled Atia'),
  ('28', 'Ouled Derradj'),
  ('28', 'Ouled Madhi'),
  ('28', 'Ouled Mansour'),
  ('28', 'Ouled Sidi Brahim'),
  ('28', 'Ouled Slimane'),
  ('28', 'Oultem'),
  ('28', 'Sidi Assa'),
  ('28', 'Sidi Ameur'),
  ('28', 'Sidi Hadjeres'),
  ('28', 'Sidi M''Hamed'),
  ('28', 'Slim'),
  ('28', 'Souamaa'),
  ('28', 'Tamsa'),
  ('28', 'Tarmount'),
  ('28', 'Zarzour'),
  ('29', 'An Fares'),
  ('29', 'An Fekan'),
  ('29', 'An Ferah'),
  ('29', 'An Fras'),
  ('29', 'Alamia'),
  ('29', 'Aouf'),
  ('29', 'Beniane'),
  ('29', 'Bou Hanifia'),
  ('29', 'Bou Henni'),
  ('29', 'Chorfa'),
  ('29', 'El Bordj'),
  ('29', 'El Gaada'),
  ('29', 'El Ghomri'),
  ('29', 'El Guettana'),
  ('29', 'El Keurt'),
  ('29', 'El Menaouer'),
  ('29', 'Ferraguig'),
  ('29', 'Froha'),
  ('29', 'Gharrous'),
  ('29', 'Guerdjoum'),
  ('29', 'Ghriss'),
  ('29', 'Hachem'),
  ('29', 'Hacine'),
  ('29', 'Khalouia'),
  ('29', 'Makdha'),
  ('29', 'Mamounia'),
  ('29', 'Maoussa'),
  ('29', 'Mascara'),
  ('29', 'Matemore'),
  ('29', 'Mocta Douz'),
  ('29', 'Mohammadia'),
  ('29', 'Nesmoth'),
  ('29', 'Oggaz'),
  ('29', 'Oued El Abtal'),
  ('29', 'Oued Taria'),
  ('29', 'Ras El An Amirouche'),
  ('29', 'Sedjerara'),
  ('29', 'Sehailia'),
  ('29', 'Sidi Abdeldjebar'),
  ('29', 'Sidi Abdelmoumen'),
  ('29', 'Sidi Kada'),
  ('29', 'Sidi Boussaid'),
  ('29', 'Sig'),
  ('29', 'Tighennif'),
  ('29', 'Tizi'),
  ('29', 'Zahana'),
  ('29', 'Zelmata'),
  ('30', 'An Beida'),
  ('30', 'Hassi Ben Abdellah'),
  ('30', 'Hassi Messaoud'),
  ('30', 'N''Goussa'),
  ('30', 'Ouargla'),
  ('30', 'Rouissat'),
  ('30', 'Sidi Khouiled'),
  ('31', 'Oran'),
  ('31', 'Gdyel'),
  ('31', 'Bir El Djir'),
  ('31', 'Hassi Bounif'),
  ('31', 'Es Senia'),
  ('31', 'Arzew'),
  ('31', 'Bethioua'),
  ('31', 'Marsat El Hadjadj'),
  ('31', 'An El Turk'),
  ('31', 'El Anor'),
  ('31', 'Oued Tlelat'),
  ('31', 'Tafraoui'),
  ('31', 'Sidi Chami'),
  ('31', 'Boufatis'),
  ('31', 'Mers El Kbir'),
  ('31', 'Bou Sfer'),
  ('31', 'El Kerma'),
  ('31', 'El Braya'),
  ('31', 'Hassi Ben Okba'),
  ('31', 'Ben Freha'),
  ('31', 'Hassi Mefsoukh'),
  ('31', 'Sidi Benyebka'),
  ('31', 'Misserghin'),
  ('31', 'Boutlelis'),
  ('31', 'An El Kerma'),
  ('31', 'An El Bia'),
  ('32', 'El Bayadh'),
  ('32', 'Rogassa'),
  ('32', 'Stitten'),
  ('32', 'Brezina'),
  ('32', 'Ghassoul'),
  ('32', 'Boualem'),
  ('32', 'El Abiodh Sidi Cheikh'),
  ('32', 'An El Orak'),
  ('32', 'Arbaouat'),
  ('32', 'Bougtoub'),
  ('32', 'El Kheiter'),
  ('32', 'Kef El Ahmar'),
  ('32', 'Boussemghoun'),
  ('32', 'Chellala'),
  ('32', 'Kraakda'),
  ('32', 'El Bnoud'),
  ('32', 'Cheguig'),
  ('32', 'Sidi Ameur'),
  ('32', 'El Mehara'),
  ('32', 'Tousmouline'),
  ('32', 'Sidi Slimane'),
  ('32', 'Sidi Tifour'),
  ('33', 'Illizi'),
  ('33', 'Debdeb'),
  ('33', 'Bordj Omar Driss'),
  ('33', 'In Amenas'),
  ('34', 'An Taghrout'),
  ('34', 'An Tesra'),
  ('34', 'Belimour'),
  ('34', 'Ben Daoud'),
  ('34', 'Bir Kasdali'),
  ('34', 'Bordj Bou Arreridj'),
  ('34', 'Bordj Ghdir'),
  ('34', 'Bordj Zemoura'),
  ('34', 'Colla'),
  ('34', 'Djaafra'),
  ('34', 'El Ach'),
  ('34', 'El Achir'),
  ('34', 'El Anseur'),
  ('34', 'El Hamadia'),
  ('34', 'El Main'),
  ('34', 'El M''hir'),
  ('34', 'Ghilassa'),
  ('34', 'Haraza'),
  ('34', 'Hasnaoua'),
  ('34', 'Khelil'),
  ('34', 'Ksour'),
  ('34', 'Mansoura'),
  ('34', 'Medjana'),
  ('34', 'Ouled Brahem'),
  ('34', 'Ouled Dahmane'),
  ('34', 'Ouled Sidi Brahim'),
  ('34', 'Rabta'),
  ('34', 'Ras El Oued'),
  ('34', 'Sidi Embarek'),
  ('34', 'Tefreg'),
  ('34', 'Taglait'),
  ('34', 'Teniet En Nasr'),
  ('34', 'Tassameurt'),
  ('34', 'Tixter'),
  ('36', 'An El Assel'),
  ('36', 'An Kerma'),
  ('36', 'Asfour'),
  ('36', 'Ben Mehidi'),
  ('36', 'Berrihane'),
  ('36', 'Besbes'),
  ('36', 'Bougous'),
  ('36', 'Bouhadjar'),
  ('36', 'Bouteldja'),
  ('36', 'Chebaita Mokhtar'),
  ('36', 'Chefia'),
  ('36', 'Chihani'),
  ('36', 'Dran'),
  ('36', 'Echatt'),
  ('36', 'El Aioun'),
  ('36', 'El Kala'),
  ('36', 'El Tarf'),
  ('36', 'Hammam Beni Salah'),
  ('36', 'Lac des Oiseaux'),
  ('36', 'Oued Zitoun'),
  ('36', 'Raml Souk'),
  ('36', 'Souarekh'),
  ('36', 'Zerizer'),
  ('36', 'Zitouna'),
  ('37', 'Oum el Assel'),
  ('37', 'Tindouf'),
  ('38', 'Ammari'),
  ('38', 'Beni Chaib'),
  ('38', 'Beni Lahcene'),
  ('38', 'Boucaid'),
  ('38', 'Bordj Bou Naama'),
  ('38', 'Bordj El Emir Abdelkader'),
  ('38', 'Khemisti'),
  ('38', 'Larbaa'),
  ('38', 'Lardjem'),
  ('38', 'Layoune'),
  ('38', 'Lazharia'),
  ('38', 'Maacem'),
  ('38', 'Melaab'),
  ('38', 'Ouled Bessem'),
  ('38', 'Sidi Abed'),
  ('38', 'Sidi Boutouchent'),
  ('38', 'Sidi Lantri'),
  ('38', 'Sidi Slimane'),
  ('38', 'Tamalaht'),
  ('38', 'Theniet El Had'),
  ('38', 'Tissemsilt'),
  ('38', 'Youssoufia'),
  ('39', 'El Oued'),
  ('39', 'Robbah'),
  ('39', 'Oued El Alenda'),
  ('39', 'Bayadha'),
  ('39', 'Nakhla'),
  ('39', 'Guemar'),
  ('39', 'Kouinine'),
  ('39', 'Reguiba'),
  ('39', 'Hamraia'),
  ('39', 'Taghzout'),
  ('39', 'Debila'),
  ('39', 'Hassani Abdelkrim'),
  ('39', 'Hassi Khalifa'),
  ('39', 'Taleb Larbi'),
  ('39', 'Douar El Ma'),
  ('39', 'Sidi Aoun'),
  ('39', 'Trifaoui'),
  ('39', 'Magrane'),
  ('39', 'Beni Guecha'),
  ('39', 'Ourmas'),
  ('39', 'El Ogla'),
  ('39', 'Mih Ouansa'),
  ('40', 'An Touila'),
  ('40', 'Babar'),
  ('40', 'Baghai'),
  ('40', 'Bouhmama'),
  ('40', 'Chechar'),
  ('40', 'Chelia'),
  ('40', 'Djellal'),
  ('40', 'El Hamma'),
  ('40', 'El Mahmal'),
  ('40', 'El Oueldja'),
  ('40', 'Ensigha'),
  ('40', 'Kais'),
  ('40', 'Khenchela'),
  ('40', 'Khirane'),
  ('40', 'M''Sara'),
  ('40', 'M''Toussa'),
  ('40', 'Ouled Rechache'),
  ('40', 'Remila'),
  ('40', 'Tamza'),
  ('40', 'Taouzient'),
  ('40', 'Yabous'),
  ('41', 'Souk Ahras'),
  ('41', 'Sedrata'),
  ('41', 'Hanancha'),
  ('41', 'Mechroha'),
  ('41', 'Ouled Driss'),
  ('41', 'Tiffech'),
  ('41', 'Zaarouria'),
  ('41', 'Taoura'),
  ('41', 'Drea'),
  ('41', 'Heddada'),
  ('41', 'Khedara'),
  ('41', 'Merahna'),
  ('41', 'Ouled Moumene'),
  ('41', 'Bir Bou Haouch'),
  ('41', 'M''daourouch'),
  ('41', 'Oum El Adhaim'),
  ('41', 'An Zana'),
  ('41', 'An Soltane'),
  ('41', 'Ouillen'),
  ('41', 'Sidi Fredj'),
  ('41', 'Safel El Ouiden'),
  ('41', 'Ragouba'),
  ('41', 'Khemissa'),
  ('41', 'Oued Keberit'),
  ('41', 'Terraguelt'),
  ('41', 'Zouabi'),
  ('42', 'Tipaza'),
  ('42', 'Menaceur'),
  ('42', 'Larhat'),
  ('42', 'Douaouda'),
  ('42', 'Bourkika'),
  ('42', 'Khemisti'),
  ('42', 'Aghbal'),
  ('42', 'Hadjout'),
  ('42', 'Sidi Amar'),
  ('42', 'Gouraya'),
  ('42', 'Nador'),
  ('42', 'Chaiba'),
  ('42', 'An Tagourait'),
  ('42', 'Cherchell'),
  ('42', 'Damous'),
  ('42', 'Merad'),
  ('42', 'Fouka'),
  ('42', 'Bou Ismal'),
  ('42', 'Ahmar El An'),
  ('42', 'Bouharoun'),
  ('42', 'Sidi Ghiles'),
  ('42', 'Messelmoun'),
  ('42', 'Sidi Rached'),
  ('42', 'Kola'),
  ('42', 'Attatba'),
  ('42', 'Sidi Semiane'),
  ('42', 'Beni Milleuk'),
  ('42', 'Hadjeret Ennous'),
  ('43', 'Ahmed Rachedi'),
  ('43', 'An Beida Harriche'),
  ('43', 'An Mellouk'),
  ('43', 'An Tine'),
  ('43', 'Amira Arrs'),
  ('43', 'Benyahia Abderrahmane'),
  ('43', 'Bouhatem'),
  ('43', 'Chelghoum Laid'),
  ('43', 'Chigara'),
  ('43', 'Derradji Bousselah'),
  ('43', 'El Mechira'),
  ('43', 'Elayadi Barbes'),
  ('43', 'Ferdjioua'),
  ('43', 'Grarem Gouga'),
  ('43', 'Hamala'),
  ('43', 'Mila'),
  ('43', 'Minar Zarza'),
  ('43', 'Oued Athmania'),
  ('43', 'Oued Endja'),
  ('43', 'Oued Seguen'),
  ('43', 'Ouled Khalouf'),
  ('43', 'Rouached'),
  ('43', 'Sidi Khelifa'),
  ('43', 'Sidi Merouane'),
  ('43', 'Tadjenanet'),
  ('43', 'Tassadane Haddada'),
  ('43', 'Teleghma'),
  ('43', 'Terrai Bainen'),
  ('43', 'Tessala Lemta'),
  ('43', 'Tiberguent'),
  ('43', 'Yahia Beni Guecha'),
  ('43', 'Zeghaia'),
  ('48', 'An Rahma'),
  ('48', 'An Tarek'),
  ('48', 'Ammi Moussa'),
  ('48', 'Belassel Bouzegza'),
  ('48', 'Bendaoud'),
  ('48', 'Beni Dergoun'),
  ('48', 'Beni Zentis'),
  ('48', 'Dar Ben Abdellah'),
  ('48', 'Djidioua'),
  ('48', 'El Guettar'),
  ('48', 'El Hamadna'),
  ('48', 'El Hassi'),
  ('48', 'El Matmar'),
  ('48', 'El Ouldja'),
  ('48', 'Had Echkalla'),
  ('48', 'Hamri'),
  ('48', 'Kalaa'),
  ('48', 'Lahlef'),
  ('48', 'Mazouna'),
  ('48', 'Mediouna'),
  ('48', 'Mendes'),
  ('48', 'Merdja Sidi Abed'),
  ('48', 'Ouarizane'),
  ('48', 'Oued Essalem'),
  ('48', 'Oued Rhiou'),
  ('48', 'Ouled Aiche'),
  ('48', 'Oued El Djemaa'),
  ('48', 'Ouled Sidi Mihoub'),
  ('48', 'Ramka'),
  ('48', 'Relizane'),
  ('48', 'Sidi Khettab'),
  ('48', 'Sidi Lazreg'),
  ('48', 'Sidi M''Hamed Ben Ali'),
  ('48', 'Sidi M''Hamed Benaouda'),
  ('48', 'Sidi Saada'),
  ('48', 'Souk El Had'),
  ('48', 'Yellel'),
  ('48', 'Zemmora'),
  ('49', 'Charouine'),
  ('49', 'Ksar Kaddour'),
  ('49', 'Timimoun'),
  ('49', 'Ouled Sad'),
  ('49', 'Tinerkouk'),
  ('49', 'Deldoul'),
  ('49', 'Metarfa'),
  ('49', 'Aougrout'),
  ('49', 'Talmine'),
  ('49', 'Ouled Assa'),
  ('50', 'Bordj Badji Mokhtar'),
  ('50', 'Timiaouine'),
  ('51', 'Besbes'),
  ('51', 'Doucen'),
  ('51', 'Ech Chaba'),
  ('51', 'Ouled Djellal'),
  ('51', 'Ras El Miaad'),
  ('51', 'Sidi Khaled'),
  ('53', 'In Ghar'),
  ('53', 'In Salah'),
  ('53', 'Foggaret Ezzaouia'),
  ('54', 'In Guezzam'),
  ('54', 'Tin Zaouatine'),
  ('55', 'Benaceur'),
  ('55', 'Blidet Amor'),
  ('55', 'El Allia'),
  ('55', 'El Borma'),
  ('55', 'El Hadjira'),
  ('55', 'Megarine'),
  ('55', 'M''Naguer'),
  ('55', 'Nezla'),
  ('55', 'Sidi Slimane'),
  ('55', 'Taibet'),
  ('55', 'Tamacine'),
  ('55', 'Tebesbest'),
  ('55', 'Touggourt'),
  ('55', 'Zaouia El Abidia'),
  ('56', 'Djanet'),
  ('56', 'Bordj El Haouas'),
  ('57', 'Still'),
  ('57', 'M''Rara'),
  ('57', 'Sidi Khellil'),
  ('57', 'Tendla'),
  ('57', 'El M''Ghair'),
  ('57', 'Djamaa'),
  ('57', 'Oum Touyour'),
  ('57', 'Sidi Amrane'),
  ('58', 'El Menia'),
  ('58', 'Hassi Fehal'),
  ('58', 'Hassi Gara')
) as v(wilaya_code, name)
join public.wilayas w on w.code = v.wilaya_code
on conflict (wilaya_id, name) do nothing;
